version: 2
jobs:
  build:
    working_directory: ~/laravel5.5
    docker:
      - image: ucreateit/laravel-pgsql:0.0.1
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
             sudo apt-get update && sudo apt-get -f install && sudo apt-get install wget
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

